blogs/urls.py
from django.urls import path

from blogs import views



app_name = 'blogs'

urlpatterns = [
    path('', views.home_page, name='home'),
    path('post/<int:pk>', views.PostView.as_view(), name='post'),
    path('featured', views.FeaturedListView.as_view(), name='featured'),
    path('category/<int:id>', views.CategoryListView.as_view(), name='category'),
    path('search/', views.SearchReviewsView.as_view(), name='search'),
    path('search-user/', views.SearchUsersView.as_view(), name='search-user'),
    path('search-album/', views.SearchAlbumsView.as_view(), name='search-album'),
    path('search-artist/', views.SearchArtistView.as_view(), name='search-artist'),
    path('newpost/', views.create_post, name='newpost'),
    path('album/<int:pk>', views.AlbumDetailView.as_view(), name='album'),
    path('artist/<int:pk>', views.ArtistDetailView.as_view(), name='artist'),
    
]

core/core/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('blogs.urls')),
    path('', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views
from django.views.generic import TemplateView


app_name = 'users'

urlpatterns = [
    path('registration/', views.UserRegistration.as_view(), name = 'registration'),
    path('success/', TemplateView.as_view(template_name= 'users/success_registration.html'), name = 'success'),
    path('profile/<int:user_id>', views.ProfileView.as_view(), name='profile'),
    path('profile/users/seguir-usuario/<int:user_id>/', views.seguir_usuario, name='seguir-usuario'),

]
    

    
    

blogs/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils import timezone
from django.conf import settings
from django.dispatch import receiver
from django.db.models.signals import pre_save
# Create your models here.


class Artist(models.Model):
    name = models.CharField(max_length=100, unique=True)
    
    def __str__ (self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("blogs:artist", kwargs={"pk": self.pk})

class Album(models.Model):
    title = models.CharField(max_length=225)
    date_created = models.DateField()
    author = models.ForeignKey(Artist, on_delete=models.PROTECT, default=False)
    categories = models.ManyToManyField('Category')
    image = models.ImageField(upload_to='albums/', blank=True, null=True)
    
    def __str__ (self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("blogs:album", kwargs={"pk": self.pk})
    


class Post(models.Model):
    title = models.CharField(max_length=225)
    date_created = models.DateTimeField(auto_now_add= True)
    content = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    album = models.ForeignKey(Album, on_delete=models.PROTECT)
    categories = models.ManyToManyField('Category',)
    
    pub_date = models.DateTimeField(default=timezone.now)
    rating = models.IntegerField(default=1, choices=zip(range(1, 6), range(1, 6)))
    lecturas = models.IntegerField(default=1)
    featured = models.FloatField(default=0)
    
    
    def get_absolute_url(self):
        return reverse("blogs:post", kwargs={"pk": self.pk})
    
    class Meta:
        ordering = ['-date_created']
    
    def __str__ (self):
        return self.title
    
    
    def featured_calc(self):
        a = 1  # ponderación cantidad de lecturas
        b = 30  # ponderación cantidad de publicaciones del autor
        c = 30  # ponderación cantidad de días desde que se publicó
        fecha_referencia = timezone.now()
        diferencia_dias = (fecha_referencia - self.pub_date).days
        featured_number = a * self.lecturas + b * self.author.cantidad_publicaciones() - c * diferencia_dias
        return float(featured_number)

    def save(self, *args, **kwargs):
        self.featured = self.featured_calc()  # Calcula 'featured' antes de guardar
        super(Post, self).save(*args, **kwargs)

    # Resto de tu modelo

# Signal para calcular 'featured' antes de guardar el objeto
@receiver(pre_save, sender=Post)
def calculate_featured(sender, instance, **kwargs):
    instance.featured = instance.featured_calc()
    
    
    
class Category(models.Model):
    title = models.CharField(max_length=225)
    sluge = models.SlugField(unique=True)
    
    class Meta:
        verbose_name_plural = 'categories'
    
    def get_absolute_url(self):
        return reverse("blogs:post", kwargs={"slug": self.sluge})
    def __str__(self):
        return self.title
    

class Comment(models.Model):
    content = models.TextField(max_length=1000, help_text="ingrese un comentario")
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    post_date = models.DateTimeField(auto_now_add= True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    
    class Meta:
        ordering= ['-post_date']
    
    def __str__(self):
        len_title = 15
        if len(self.content)> len_title:
            return self.content[:len_title]+'...'
        return self.content
    

users/models.py
from django.db import models
from django.contrib.auth.models import AbstractUser
from blogs.models import Post
from django.urls import reverse


# Create your models here.

class User(AbstractUser):
    profile_pic = models.ImageField(upload_to='profile_pics/', blank=True, null=True,default='default.jpg')
    following = models.ManyToManyField("self", symmetrical=False, blank=True, related_name="followers")
    
    

    def __str__(self):
        return f'{self.username}'
    
    def cantidad_publicaciones(self):
        return Post.objects.filter(author=self).count()
    
    def get_absolute_url(self):
        return reverse("users:profile", kwargs={"user_id": self.id})
    
    def rating(self):
        # Obtén todos los posts del usuario
        user_posts = Post.objects.filter(author=self)
        
        # Inicializa variables para el cálculo del promedio
        total_rating = 0
        total_posts = 0
        
        # Calcula la suma total de los ratings y cuenta los posts
        for post in user_posts:
            total_rating += post.rating
            total_posts += 1
        
        # Evita la división por cero
        if total_posts > 0:
            # Calcula el promedio
            average_rating = total_rating / total_posts
            return average_rating
        else:
            return 0  # Otra valor predeterminado apropiado si el usuario no tiene publicaciones

 

blogs/forms.py
from django import forms
from blogs.models import Comment
from blogs.models import  Post


class PostCommentForm(forms.ModelForm):
    content = forms.CharField(label='Ingrese un comentario')
    class Meta:
        model = Comment
        fields = ['content']
        
        
class ReviewForm(forms.ModelForm):
    content = forms.CharField(label='Ingrese una review')
    class Meta:
        model = Post
        fields = ('title','content','album', 'rating')

blogs/views.py
from typing import Any
from django.shortcuts import render, redirect

from blogs.models import Post, Album, Artist
from users.models import User
from django.views import generic, View
from django.views.generic.detail import SingleObjectMixin
from django.views.generic import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.urls import reverse
from django.db.models import Q
from blogs.forms import PostCommentForm, ReviewForm
import random
from django.shortcuts import get_object_or_404

# Create your views here.


def home_page(request):
    if request.user.is_authenticated:
        # Obtén los usuarios a los que sigue el usuario actual
        following_users = request.user.following.all()
        
        # Filtra los Post de los usuarios a los que sigues
        posts = Post.objects.filter(
            author__in=following_users,
            pub_date__lte=timezone.now()
        ).order_by('-featured')
    else:
        # Si el usuario no ha iniciado sesión, muestra todos los Post
        posts = Post.objects.filter(pub_date__lte=timezone.now())
    all_albums = Album.objects.all()
    albums = random.sample(list(all_albums), 3)
    context= {
        
        'post_list' : posts,
        'albums' : albums
    }
    
    return render(request, 'blogs/home_page.html', context=context)

def create_post( request):
    albums = Album.objects.all()
    
    if request.method == 'POST':
        form = ReviewForm(request.POST, request.FILES)
        if form.is_valid():
            new_post = form.save(commit=False)
            #new_post.categories = new_post.album.categories
            new_post.author = request.user  # Asigna el autor actual
            
            new_post.save()
            return redirect('blogs:home')  # Redirige a la página deseada después de crear el post
    else:
        form = ReviewForm()
    return render(request, 'blogs/new_post.html', {'form': form, 'album':albums})



class PostDetailView(generic.DetailView):
    model = Post
    queryset = posts = Post.objects.filter(
        pub_date__lte=timezone.now()
    )
    
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['form']= PostCommentForm()
        return context

class PostCommentFormView(LoginRequiredMixin, SingleObjectMixin, FormView):
    template_name = 'blogs/post_detail.html'
    form_class = PostCommentForm
    model = Post
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)
    
    def form_valid(self, form):
        f = form.save(commit = False)
        f.author = self.request.user
        f.post = self.object
        f.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('blogs:post', kwargs= {'pk':self.object.pk}) + '#comments-section'
    
class PostView(View):
    
    def get(s3elf, request,*args,**kwargs):
        
        post = get_object_or_404(Post, pk=kwargs['pk'])  # Asegúrate de usar el nombre correcto del parámetro
        post.lecturas += 1  # Incrementa las lecturas
        post.save()
        
        view = PostDetailView.as_view()
        return view(request, *args, **kwargs)
    
    def post(s3elf, request,*args,**kwargs):
        view = PostCommentFormView.as_view()
        return view(request,*args,**kwargs)
    
    
class FeaturedListView(generic.ListView):
    moodel = Post
    template_name = 'blogs/results.html'
    
    
    def get_queryset(self):
        query = Post.objects.filter(
            featured__gte=150).filter(
        pub_date__lte=timezone.now()
    )
        
        return query
    
    
    
class CategoryListView(generic.ListView):
    model = Album
    template_name = "blogs/categories_results.html"

    def get_queryset(self):
        query = self.request.path.replace('/category/','')
        
        album_list = Album.objects.filter(categories__id = query)
        return album_list
    
   
    
class SearchReviewsView(generic.TemplateView):
    template_name = "blogs/results.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('search')
        
        post_list = Post.objects.filter(
            Q(title__icontains=query) | Q(album__categories__title__icontains=query) | Q(author__username__icontains=query)
        ).filter(pub_date__lte=timezone.now()).distinct()

       
        results = {
            'post_list': post_list,
            
            'query':query
        }

        context['results'] = results

        return results
    
    
    
class SearchUsersView(generic.TemplateView):
    template_name = "blogs/user_results.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('search')
        
        

        user_list = User.objects.filter(Q(username__icontains=query)).distinct()
      
        results = {
            
            'user_list': user_list,
            
            'query':query
        }

        context['results'] = results

        return results
    
class SearchAlbumsView(generic.TemplateView):
    template_name = "blogs/album_results.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('search')
        
        
        album_list = Album.objects.filter(Q(title__icontains=query)| Q(categories__title__icontains=query)).distinct()
        results = {
            
            'album_list':album_list,
            'query':query,
        }

        context['results'] = results

        return results
    

class SearchArtistView(generic.TemplateView):
    template_name = "blogs/artist_results.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('search')
        
        
        artist_list = Artist.objects.filter(Q(name__icontains=query)).distinct()
        
        results = {
            'artist_list': artist_list,
            
            'query':query,
        }

        context['results'] = results

        return results





    
class AlbumDetailView(generic.DetailView):
    model = Album
    template_name = 'blogs/album_detail.html'
    
    
    
    def get_object(self, queryset=None):
        album_id = self.kwargs.get('pk')  # Obtén el user_id desde los parámetros de la URL
        return get_object_or_404(Album, pk=album_id)


class ArtistDetailView(generic.ListView):
    model = Album
    template_name = 'blogs/artist_detail.html'
    context_object_name = 'album_list'

    def get_queryset(self):
        # Obtén el artista a través de su clave primaria (pk) desde la URL
        artist = (Artist.objects.get(pk=self.kwargs['pk']))
        # Filtra los álbumes relacionados con el artista
        return Album.objects.filter(author=artist).order_by('-date_created')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Agrega el artista al contexto
        context['artist'] = Artist.objects.get(pk=self.kwargs['pk'])
        return context

blogs/templates/blogs/album_detail.html
{% extends 'base.html' %}
{% load markdown_extras %}
{% load crispy_forms_tags %}

{% load static %}
<div class="container-xxl bd-gutter mt-3 my-md-4 bd-layout">

{% block content %} 

<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">



    <main class="container">

        <div class="row g-5">
            <div class="col-md-8">

                <div class="row">
                    <div class="d-flex justify-content-between">
                        <h1>{{ album.title }}</h1>
                        <div class="align-self-end">Publicado: {{ album.date_created }}</div>
                    </div>
                </div>
                <hr class="d-none d-md-block my-2 mb-3 mt-2">
                {% if album.image %}
                    <div class="text-center">
                        <img src="{{ album.image.url }}" class="img-fluid" style="max-width: 200px; max-height: 200px" alt="thumbnail">
                    </div>
                {% else %}
                    <strong>No Album Image</strong>
                {% endif %}
                <hr>
                <h4>{{ album.author.name }}
                <hr>
                <h6>Categories:</h6>
                    <ul>
                    {% for category in album.categories.all %}
                        <li>{{ category.title }}</li>
                    {% endfor %}
                    </ul>
                    <hr>                


            </div>

            <div class="col-md-4">
                <div class="position-sticky" style="top: 2rem;">
                    <div class="p-4">
                        <a class="btn btn-outline-primary ms-2" href="{% url 'blogs:newpost' %}" 
                        role="button" style="width: 300px; height: 150px; display: flex; justify-content: center; align-items: center;">Nueva Publicación</a>

                    </div>
                </div>
            </div>
            
        </div>
        
        
    </main>
    
</div>

{% endblock content %}

blogs/templates/blogs/album_results.html
{% extends 'base.html' %}
{% block content %} 



<nav aria-label="">
    <ul class="pagination pagination-lg">
        <li class="page-item"><a class="page-link" href="{% url 'blogs:search' %}?search={{ query }}">Reviews</a></li>
      <li class="page-item"><a class="page-link" href="{% url 'blogs:search-user' %}?search={{ query }}">Users</a></li>
      <li class="page-item active" aria-current="page">
        <span class="page-link">Albums</span>
      </li>
      <li class="page-item"><a class="page-link" href="{% url 'blogs:search-artist' %}?search={{ query }}">Artists</a></li>
    </ul>
</nav>

{% if album_list %}
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>#</th>
            <th>Title</th>
            <th>Cover</th>
            <th>Date of creation</th>
        </tr>
    </thead>
    <tbody>
        
        {% for album in album_list %}
            <tr class="table-primary">
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{{ album.get_absolute_url }}" class="text-black" style="text-decoration: none">{{ album.title }}</a></td>
                {% if user.profile_pic %}
                    <td><a href="{{ album.get_absolute_url }}"><img src="{{ album.image.url }}" class = "img-fluid" style="width: 80px; height: 80px; object-fit: cover;" alt="thumbnail" ></a></td>
                {% else %}
                    <td>Image</td>
                {% endif %}
                <td>{{ album.date_created }}</td>
            </tr>
            
        {% endfor %}
    </tbody>
</table>
{% endif %}
{% endblock %}

blogs/templates/blogs/artist_results.html
{% extends 'base.html' %}
{% block content %} 



<nav aria-label="">
    <ul class="pagination pagination-lg">
        <li class="page-item"><a class="page-link" href="{% url 'blogs:search' %}?search={{ query }}">Reviews</a></li>
        <li class="page-item"><a class="page-link" href="{% url 'blogs:search-user' %}?search={{ query }}">Users</a></li>
        <li class="page-item"><a class="page-link" href="{% url 'blogs:search-album' %}?search={{ query }}">Albums</a></li>
        <li class="page-item active" aria-current="page">
            <span class="page-link">Artists</span>
        </li>
        
    </ul>
  </nav>


{% if artist_list %}
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>#</th>
            <th>Name</th>
            <th>Albums</th>
        </tr>
    </thead>
    <tbody>
        
        {% for artist in artist_list %}
            <tr class="table-primary">
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{{ artist.get_absolute_url }}" class="text-black" style="text-decoration: none">{{ artist.name }}</a></td>
                <td>
                    {% for album in artist.album_set.all %}
                        {{ album.title }}
                        {% if not forloop.last %}, {% endif %}
                    {% endfor %}
                </td>
            </tr>
            
        {% endfor %}
    </tbody>
</table>
{% endif %}



{% endblock %}

blogs/templates/blogs/home_page.html
{% extends 'base.html' %}

{% block content %} 
<div class="container-xxl bd-gutter mt-3 my-md-4 bd-layout">

    <main class="container">

        <div class="row g-5">
    
            <div class="col-md-12">
                {% include "blogs/featured.html" %}
            </div>
    
        </div>

        <div class="row g-5">
            <div class="col-md-8">
                <h3 class="pb-4 mb-4 fst-italic border-bottom">
                    Reviews
                </h3>
                {% for post in post_list %}
                    <article class="blog-post" style="height: 150px;" >
                        <div class="d-flex">  
                            <div class="flex-grow-1 ms-3">
                                <h6 class="blog-post-meta"> 
                                    <a  style="text-decoration:none" class="text-black font-weight-lighter" href="{% url 'users:profile' post.author.id %}" role="button" >@{{ post.author }}</a></h6>  
                                <h2 class="blog-post-title mb-1">
                                    <a href="{{ post.get_absolute_url }}" style="text-decoration: none" class="text-black">
                                        {{ post.title }}
                                    </a>
                                </h2>
                                <p class="blog-post-meta">{{ post.pub_date.date }}</p>
                                
                            </div>
                            <div class="flex-shrink-0">  
                                {% if post.album.image %}
                                <img src="{{ post.album.image.url }}" class="img-fluid" style="width: 100px; height: 100px; object-fit: cover;" alt="image">
                                {% else %}
                                    <td>Image</td>
                                {% endif %}
                            </div>
                        </div>
                        <hr>
                    </article>
                {% endfor %}

            </div>

            <div class="col-md-4">
                <div class="position-sticky" style="top: 2rem;">
                    <div class="p-4 mb-3 bg-light rounded">
                        <h4 class="fst-italic">Sobre</h4>
                        <p class="mb-0">¿Buscas la banda sonora perfecta para cada momento de tu vida? Bienvenido a tu fuente definitiva de reseñas de música que te harán vibrar. 
                            Sumérgete en un mundo de notas y emociones mientras exploramos y calificamos las últimas canciones y álbumes que están causando sensación en la escena musical.</p>
                    </div>
                    
                    <div class="p-4">
                        <a class="btn btn-outline-primary ms-2" href="{% url 'blogs:newpost' %}" role="button" >Nueva Publicacion</a>
                    </div>
                </div>
            </div>
        </div>

    </main>
</div>
{% endblock content %}

blogs/templates/blogs/post_detail.html
{% extends 'base.html' %}
{% load markdown_extras %}
{% load crispy_forms_tags %}

{% load static %}
<div class="container-xxl bd-gutter mt-3 my-md-4 bd-layout">

{% block content %} 

<link rel="stylesheet" type="text/css" href="{% static 'css/styles.css' %}">



    <main class="container">

        <div class="row g-5">
            <div class="col-md-12">

                <div class="row">
                    <div class="d-flex justify-content-between">
                        <h1>{{ post.title }}</h1>
                        <div class="align-self-end">Publicado: {{ post.pub_date.date }}</div>
                    </div>
                </div>
                <hr class="d-none d-md-block my-2 mb-3 mt-2">
                {% if post.album.image %}
                    <div class="text-center">
                        <img src="{{ post.album.image.url }}" class="img-fluid" style="max-width: 250px; max-height: 250px" alt="thumbnail">
                    </div>
                {% else %}
                    <strong>No Album Image</strong>
                {% endif %}
                <!-- Mostrar el puntaje con estrellas -->
                


                <div class="d-flex justify-content-between">
                    <div id="rate" data-rating="{{ post.rating }}"></div>
                    <div>
                        <p class="font-weight-bolder"> Lecturas: {{ post.lecturas }}</p>
                        
                    </div>
                    
                </div>
                <hr>
                
                


                
                <p>{{ post.content | markdown | safe }}</p>
               
                
                
                    
                

                

                <h3 id="comments-section">Comentarios</h3>

                <hr class="d-none d-md-block my-2 mb-3 mt-2">

                <form method="post" >
                    {% csrf_token %}
                    <h1 class="h3 mb-3 fw-normal"></h1>
                    {{ form|crispy }}
                    <button class=" btn  btn-primary " type="submit">Enter</button>
                </form>
                <hr class="d-none d-md-block my-2 mb-3 mt-2">

                {% for comment in post.comment_set.all %}
                    <div class="mt-4 mb-2 border border-opacity-10 rounded p-1">
                        <div class="row">
                            <div class="col-8 d-flex">
                                <h5>{{ comment.author.username }}</h5>
                                <span>- {{ comment.post_date }}</span>
                            </div>
                            <div class="col-4 text-end">
                            </div>
                        </div>
                        {{ comment.content }}
                    </div>
                {% endfor %}

            </div>
        </div>

    </main>
</div>

{% endblock content %}

blogs/templates/blogs/results.html
{% extends 'base.html' %}
{% block content %} 


{% if query %}
<nav aria-label="">
    <ul class="pagination pagination-lg">
      <li class="page-item active" aria-current="page">
        <span class="page-link">Reviews</span>
      </li>
      <li class="page-item"><a class="page-link" href="{% url 'blogs:search-user' %}?search={{ query }}">Users</a></li>
      <li class="page-item"><a class="page-link" href="{% url 'blogs:search-album' %}?search={{ query }}">Albums</a></li>
      <li class="page-item"><a class="page-link" href="{% url 'blogs:search-artist' %}?search={{ query }}">Artists</a></li>
    </ul>
</nav>
{% endif %}

  


{% if post_list %}
<table class="table" >
    <thead class="thead-dark" >
        <tr>
            <th>#</th>
            <th>Title</th>  
            <th>Image</th>
            <th>Author</th>
            <!--<th>Rate</th>-->
            <th>Fecha de Publicacion</th>
        </tr>
    </thead>
    <tbody>
        
        {% for post in post_list %}
            <tr class="table-primary">
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{{ post.get_absolute_url }}" class="text-black" style="text-decoration: none">{{ post.title }}</a></td>
                
                {% if post.album.image %}
                    <td><img src="{{ post.album.image.url }}" class = "img-fluid" style="width: 80px; height: 80px; object-fit: cover;" alt="thumbnail" ></td>
                {% else %}
                    <td>Image</td>
                {% endif %}
                <td>{{ post.author }}</td>
                <!--<td><div id="rate" data-rating="{{ post.rating }}"></div></td>-->
                <td>{{ post.pub_date.date }}</td>
            </tr>
            
        {% endfor %}
    </tbody>
</table>
{% endif %}
<!--

{% if user_list %}
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>#</th>
            <th>Username</th>
            <th>Profile pic</th>
            <th>Detail</th>
        </tr>
    </thead>
    <tbody>
        
        {% for user in user_list %}
            <tr class="table-primary">
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{{ user.get_absolute_url }}" class="text-black" style="text-decoration: none">{{ user.username }}</a></td>
                {% if user.profile_pic %}
                    <td><img src="{{ user.profile_pic.url }}" class = "img-fluid" style="width: 80px; height: 80px; object-fit: cover;" alt="thumbnail" ></td>
                {% else %}
                    <td>Image</td>
                {% endif %}
                <td><div class="d-flex pt-1">
                    <a class="btn btn-outline-primary ms-2" href="{% url 'users:profile' user.id %}" role="button" >See profile</a>
                  </div></td>
            </tr>
            
        {% endfor %}
    </tbody>
</table>
{% endif %}


{% if album_list %}
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>#</th>
            <th>Title</th>
            <th>Cover</th>
            <th>Date of creation</th>
        </tr>
    </thead>
    <tbody>
        
        {% for album in album_list %}
            <tr class="table-primary">
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{{ album.get_absolute_url }}" class="text-black" style="text-decoration: none">{{ album.title }}</a></td>
                {% if user.profile_pic %}
                    <td><img src="{{ album.image.url }}" class = "img-fluid" style="width: 80px; height: 80px; object-fit: cover;" alt="thumbnail" ></td>
                {% else %}
                    <td>Image</td>
                {% endif %}
                <td>{{ album.date_created }}</td>
            </tr>
            
        {% endfor %}
    </tbody>
</table>
{% endif %}
-->
{% endblock %}

blogs/templates/blogs/user_results.html
{% extends 'base.html' %}
{% block content %} 



<nav aria-label="">
    <ul class="pagination pagination-lg">
        <li class="page-item"><a class="page-link" href="{% url 'blogs:search' %}?search={{ query }}">Reviews</a></li>
        <li class="page-item active" aria-current="page">
            <span class="page-link">Users</span>
        </li>
        <li class="page-item"><a class="page-link" href="{% url 'blogs:search-album' %}?search={{ query }}">Albums</a></li>
        <li class="page-item"><a class="page-link" href="{% url 'blogs:search-artist' %}?search={{ query }}">Artists</a></li>
    </ul>
  </nav>


{% if user_list %}
<table class="table">
    <thead class="thead-dark">
        <tr>
            <th>#</th>
            <th>Username</th>
            <th>Profile pic</th>
            <th>Detail</th>
        </tr>
    </thead>
    <tbody>
        
        {% for user in user_list %}
            <tr class="table-primary">
                <th scope="row">{{ forloop.counter }}</th>
                <td><a href="{{ user.get_absolute_url }}" class="text-black" style="text-decoration: none">{{ user.username }}</a></td>
                {% if user.profile_pic %}
                    <td><img src="{{ user.profile_pic.url }}" class = "img-fluid" style="width: 80px; height: 80px; object-fit: cover;" alt="thumbnail" ></td>
                {% else %}
                    <td>Image</td>
                {% endif %}
                <td><div class="d-flex pt-1">
                    <a class="btn btn-outline-primary ms-2" href="{% url 'users:profile' user.id %}" role="button" >See profile</a>
                  </div></td>
            </tr>
            
        {% endfor %}
    </tbody>
</table>
{% endif %}



{% endblock %}