blogs/urls.py
from django.urls import path

from blogs import views



app_name = 'blogs'

urlpatterns = [
    path('', views.home_page, name='home'),
    path('post/<int:pk>', views.PostView.as_view(), name='post'),
    path('featured', views.FeaturedListView.as_view(), name='featured'),
    path('category/<int:id>', views.CategoryListView.as_view(), name='category'),
    path('search/', views.SearchReviewsView.as_view(), name='search'),
    path('search-user/', views.SearchUsersView.as_view(), name='search-user'),
    path('search-album/', views.SearchAlbumsView.as_view(), name='search-album'),
    path('search-artist/', views.SearchArtistView.as_view(), name='search-artist'),
    path('newpost/', views.create_post, name='newpost'),
    path('album/<int:pk>', views.AlbumDetailView.as_view(), name='album'),
    path('artist/<int:pk>', views.ArtistDetailView.as_view(), name='artist'),
    
]

core/core/urls.py
from django.contrib import admin
from django.urls import path

urlpatterns = [
    path('admin/', admin.site.urls),
]

core/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import urls

urlpatterns = [
    path('admin/', admin.site.urls),
    path('accounts/', include('django.contrib.auth.urls')),
    path('', include('blogs.urls')),
    path('', include('users.urls')),
] + static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

users/urls.py
from django.urls import path
from users import views
from django.views.generic import TemplateView


app_name = 'users'

urlpatterns = [
    path('registration/', views.UserRegistration.as_view(), name = 'registration'),
    path('success/', TemplateView.as_view(template_name= 'users/success_registration.html'), name = 'success'),
    path('profile/<int:user_id>', views.ProfileView.as_view(), name='profile'),
    path('profile/users/seguir-usuario/<int:user_id>/', views.seguir_usuario, name='seguir-usuario'),

]
    

    
    

blogs/models.py
from django.db import models
from django.conf import settings
from django.urls import reverse
from django.utils import timezone
from django.conf import settings
from django.dispatch import receiver
from django.db.models.signals import pre_save
# Create your models here.


class Artist(models.Model):
    name = models.CharField(max_length=100, unique=True)
    
    def __str__ (self):
        return self.name
    
    def get_absolute_url(self):
        return reverse("blogs:artist", kwargs={"pk": self.pk})

class Album(models.Model):
    title = models.CharField(max_length=225)
    date_created = models.DateField()
    author = models.ForeignKey(Artist, on_delete=models.PROTECT, default=False)
    categories = models.ManyToManyField('Category')
    image = models.ImageField(upload_to='albums/', blank=True, null=True)
    
    def __str__ (self):
        return self.title
    
    def get_absolute_url(self):
        return reverse("blogs:album", kwargs={"pk": self.pk})
    


class Post(models.Model):
    title = models.CharField(max_length=225)
    date_created = models.DateTimeField(auto_now_add= True)
    content = models.TextField()
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.PROTECT)
    album = models.ForeignKey(Album, on_delete=models.PROTECT)
    categories = models.ManyToManyField('Category',)
    
    pub_date = models.DateTimeField(default=timezone.now)
    rating = models.IntegerField(default=1, choices=zip(range(1, 6), range(1, 6)))
    lecturas = models.IntegerField(default=1)
    featured = models.FloatField(default=0)
    
    
    def get_absolute_url(self):
        return reverse("blogs:post", kwargs={"pk": self.pk})
    
    class Meta:
        ordering = ['-date_created']
    
    def __str__ (self):
        return self.title
    
    
    def featured_calc(self):
        a = 1  # ponderación cantidad de lecturas
        b = 30  # ponderación cantidad de publicaciones del autor
        c = 30  # ponderación cantidad de días desde que se publicó
        fecha_referencia = timezone.now()
        diferencia_dias = (fecha_referencia - self.pub_date).days
        featured_number = a * self.lecturas + b * self.author.cantidad_publicaciones() - c * diferencia_dias
        return float(featured_number)

    def save(self, *args, **kwargs):
        self.featured = self.featured_calc()  # Calcula 'featured' antes de guardar
        super(Post, self).save(*args, **kwargs)

    # Resto de tu modelo

# Signal para calcular 'featured' antes de guardar el objeto
@receiver(pre_save, sender=Post)
def calculate_featured(sender, instance, **kwargs):
    instance.featured = instance.featured_calc()
    
    
    
class Category(models.Model):
    title = models.CharField(max_length=225)
    sluge = models.SlugField(unique=True)
    
    class Meta:
        verbose_name_plural = 'categories'
    
    def get_absolute_url(self):
        return reverse("blogs:post", kwargs={"slug": self.sluge})
    def __str__(self):
        return self.title
    

class Comment(models.Model):
    content = models.TextField(max_length=1000, help_text="ingrese un comentario")
    author = models.ForeignKey(settings.AUTH_USER_MODEL, on_delete=models.SET_NULL, null=True)
    post_date = models.DateTimeField(auto_now_add= True)
    post = models.ForeignKey(Post, on_delete=models.CASCADE)
    
    class Meta:
        ordering= ['-post_date']
    
    def __str__(self):
        len_title = 15
        if len(self.content)> len_title:
            return self.content[:len_title]+'...'
        return self.content
    

blogs/forms.py
from django import forms
from blogs.models import Comment
from blogs.models import  Post


class PostCommentForm(forms.ModelForm):
    content = forms.CharField(label='Ingrese un comentario')
    class Meta:
        model = Comment
        fields = ['content']
        
        
class ReviewForm(forms.ModelForm):
    content = forms.CharField(label='Ingrese una review')
    class Meta:
        model = Post
        fields = ('title','content','album', 'rating')

blogs/views.py
from typing import Any
from django.shortcuts import render, redirect

from blogs.models import Post, Album, Artist
from users.models import User
from django.views import generic, View
from django.views.generic.detail import SingleObjectMixin
from django.views.generic import FormView
from django.contrib.auth.mixins import LoginRequiredMixin
from django.utils import timezone
from django.urls import reverse
from django.db.models import Q
from blogs.forms import PostCommentForm, ReviewForm
import random
from django.shortcuts import get_object_or_404

# Create your views here.


def home_page(request):
    if request.user.is_authenticated:
        # Obtén los usuarios a los que sigue el usuario actual
        following_users = request.user.following.all()
        
        # Filtra los Post de los usuarios a los que sigues
        posts = Post.objects.filter(
            author__in=following_users,
            pub_date__lte=timezone.now()
        ).order_by('-featured')
    else:
        # Si el usuario no ha iniciado sesión, muestra todos los Post
        posts = Post.objects.filter(pub_date__lte=timezone.now())
    all_albums = Album.objects.all()
    albums = random.sample(list(all_albums), 3)
    context= {
        
        'post_list' : posts,
        'albums' : albums
    }
    
    return render(request, 'blogs/home_page.html', context=context)

def create_post( request):
    albums = Album.objects.all()
    
    if request.method == 'POST':
        form = ReviewForm(request.POST, request.FILES)
        if form.is_valid():
            new_post = form.save(commit=False)
            #new_post.categories = new_post.album.categories
            new_post.author = request.user  # Asigna el autor actual
            
            new_post.save()
            return redirect('blogs:home')  # Redirige a la página deseada después de crear el post
    else:
        form = ReviewForm()
    return render(request, 'blogs/new_post.html', {'form': form, 'album':albums})



class PostDetailView(generic.DetailView):
    model = Post
    queryset = posts = Post.objects.filter(
        pub_date__lte=timezone.now()
    )
    
    def get_context_data(self,**kwargs):
        context = super().get_context_data(**kwargs)
        context['form']= PostCommentForm()
        return context

class PostCommentFormView(LoginRequiredMixin, SingleObjectMixin, FormView):
    template_name = 'blogs/post_detail.html'
    form_class = PostCommentForm
    model = Post
    
    def post(self, request, *args, **kwargs):
        self.object = self.get_object()
        return super().post(request, *args, **kwargs)
    
    def form_valid(self, form):
        f = form.save(commit = False)
        f.author = self.request.user
        f.post = self.object
        f.save()
        return super().form_valid(form)
    
    def get_success_url(self):
        return reverse('blogs:post', kwargs= {'pk':self.object.pk}) + '#comments-section'
    
class PostView(View):
    
    def get(s3elf, request,*args,**kwargs):
        
        post = get_object_or_404(Post, pk=kwargs['pk'])  # Asegúrate de usar el nombre correcto del parámetro
        post.lecturas += 1  # Incrementa las lecturas
        post.save()
        
        view = PostDetailView.as_view()
        return view(request, *args, **kwargs)
    
    def post(s3elf, request,*args,**kwargs):
        view = PostCommentFormView.as_view()
        return view(request,*args,**kwargs)
    
    
class FeaturedListView(generic.ListView):
    moodel = Post
    template_name = 'blogs/results.html'
    
    
    def get_queryset(self):
        query = Post.objects.filter(
            featured__gte=150).filter(
        pub_date__lte=timezone.now()
    )
        
        return query
    
    
    
class CategoryListView(generic.ListView):
    model = Album
    template_name = "blogs/categories_results.html"

    def get_queryset(self):
        query = self.request.path.replace('/category/','')
        
        album_list = Album.objects.filter(categories__id = query)
        return album_list
    
   
    
class SearchReviewsView(generic.TemplateView):
    template_name = "blogs/results.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('search')
        
        post_list = Post.objects.filter(
            Q(title__icontains=query) | Q(album__categories__title__icontains=query) | Q(author__username__icontains=query)
        ).filter(pub_date__lte=timezone.now()).distinct()

       
        results = {
            'post_list': post_list,
            
            'query':query
        }

        context['results'] = results

        return results
    
    
    
class SearchUsersView(generic.TemplateView):
    template_name = "blogs/user_results.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('search')
        
        

        user_list = User.objects.filter(Q(username__icontains=query)).distinct()
      
        results = {
            
            'user_list': user_list,
            
            'query':query
        }

        context['results'] = results

        return results
    
class SearchAlbumsView(generic.TemplateView):
    template_name = "blogs/album_results.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('search')
        
        
        album_list = Album.objects.filter(Q(title__icontains=query)| Q(categories__title__icontains=query)).distinct()
        results = {
            
            'album_list':album_list,
            'query':query,
        }

        context['results'] = results

        return results
    

class SearchArtistView(generic.TemplateView):
    template_name = "blogs/artist_results.html"

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        query = self.request.GET.get('search')
        
        
        artist_list = Artist.objects.filter(Q(name__icontains=query)).distinct()
        
        results = {
            'artist_list': artist_list,
            
            'query':query,
        }

        context['results'] = results

        return results





    
class AlbumDetailView(generic.DetailView):
    model = Album
    template_name = 'blogs/album_detail.html'
    
    
    
    def get_object(self, queryset=None):
        album_id = self.kwargs.get('pk')  # Obtén el user_id desde los parámetros de la URL
        return get_object_or_404(Album, pk=album_id)


class ArtistDetailView(generic.ListView):
    model = Album
    template_name = 'blogs/artist_detail.html'
    context_object_name = 'album_list'

    def get_queryset(self):
        # Obtén el artista a través de su clave primaria (pk) desde la URL
        artist = (Artist.objects.get(pk=self.kwargs['pk']))
        # Filtra los álbumes relacionados con el artista
        return Album.objects.filter(author=artist).order_by('-date_created')

    def get_context_data(self, **kwargs):
        context = super().get_context_data(**kwargs)
        # Agrega el artista al contexto
        context['artist'] = Artist.objects.get(pk=self.kwargs['pk'])
        return context

blogs/templates/base.html
<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <title>Django Blog</title>
    <link rel="icon" type="image/x-icon" href="/media/logo_adobe_express.ico">
    
    <link href="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/css/bootstrap.min.css" rel="stylesheet"
          integrity="sha384-Zenh87qX5JnK2Jl0vWa8Ck2rdkQ2Bzep5IDxbcnCeuOxjzrPF/et3URy9Bv1WTRi" crossorigin="anonymous">
    <!-- Incluye la biblioteca RateYo! desde una CDN -->
    <script src="https://code.jquery.com/jquery-3.6.0.min.js"></script>

    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.css">
    <script src="https://cdnjs.cloudflare.com/ajax/libs/rateYo/2.3.2/jquery.rateyo.min.js"></script>



</head>
<body>

{% include "navbar.html" %}
{% block content %} {% endblock content %}

<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.2.2/dist/js/bootstrap.bundle.min.js"
        integrity="sha384-OERcA2EqjJCMA+/3y+gxIOqMEjwtxJY7qPCqsdltbNJuaOe923+mo//f6V8Qbsw3"
        crossorigin="anonymous"></script>

        <script>
            $(function () {
                $("#rating").rateYo({
                    rating: 0, // Valor inicial de la calificación
                    fullStar: true,
                    starWidth: '20px',
                    onSet: function (rating, rateYoInstance) {
                        // Cuando se selecciona una calificación, actualiza el campo oculto
                        $("#rating-input").val(rating);
                    }
                });
            });
        </script>
        <script>
            $(function () {
                $("#rate").rateYo({
                    rating: $('#rate').data('rating'), // Obtén la calificación del atributo data-rating
                    readOnly: true, // Establece las estrellas en modo solo lectura
                    starWidth: '25px', // Establece el ancho de las estrellas
                });
            });
        </script>

        <script>
            // Obtén el token CSRF de las cookies
            function getCSRFToken() {
                const cookieValue = document.cookie
                    .split('; ')
                    .find(row => row.startsWith("csrftoken="))
                    .split('=')[1];
                return cookieValue;
            }
        
            $(".seguir-usuario").on("click", function() {
                const button = $(this);
                const userId = button.data("usuario-id");
                const isFollowing = button.text().trim() === "Unfollow";
        
                // Obtén el token CSRF
                const csrfToken = getCSRFToken();
        
                $.ajax({
                    type: "POST",
                    url: `users/seguir-usuario/${userId}/`,
                    data: {
                        is_following: isFollowing,
                        csrfmiddlewaretoken: csrfToken
                    },
                    success: function(data) {
                        if (isFollowing) {
                            button.text("Follow");
                        } else {
                            button.text("Unfollow");
                        }
                    },
                    error: function(xhr, status, error) {
                        console.error("Error al seguir/dejar de seguir al usuario: " + error);
                    }
                });
            });
        </script>
        
            
</body>
</html>

blogs/templates/navbar.html
<nav class="navbar navbar-expand-lg bg-light">
    <div class="container-fluid">
        <a class="navbar-brand" href="/">Musi<span class="text-danger">Blog</span></a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarSupportedContent"
                aria-controls="navbarSupportedContent" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>
        <div class="collapse navbar-collapse" id="navbarSupportedContent">
            <ul class="navbar-nav me-auto mb-2 mb-lg-0">
                <li class="nav-item">
                    <a class="nav-link active" aria-current="page" href="/">Inicio</a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'blogs:featured' %}">Destacados</a>
                </li>
                
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" role="button" data-bs-toggle="dropdown"
                       aria-expanded="false">
                       Generos
                    </a>
                    <ul class="dropdown-menu">
                        {% for category in categories %}
                            <li><a class="dropdown-item"
                                href="{% url 'blogs:category' category.id %}">{{ category.title }}</a></li>
                        {% endfor %}
                    </ul>
                </li>
            </ul>
            <form class="d-flex" role="search" action="{% url 'blogs:search' %}" method="get">
                <input name="search" class="form-control me-2" type="search" placeholder="Buscar" aria-label="Search">
                <button class="btn btn-outline-success" type="submit">Buscar</button>
            </form>
            {% if user.is_authenticated %}
                <a class="btn btn-outline-primary ms-2" href="{% url 'logout' %}" role="button" >Sign Out</a>
                <a class="btn btn-outline-primary ms-2" href="{% url 'users:profile' request.user.id %}" role="button" >Profile</a>
            {% else %}
                <a class="btn btn-outline-primary ms-2" href="{% url 'login' %}" role="button" >Sign In</a>
            {% endif %}
        </div>
    </div>
</nav>